feat: Make checkout optional (#167)

diff --git a/terraform-deploy/action.yml b/terraform-deploy/action.yml
--- a/terraform-deploy/action.yml
+++ b/terraform-deploy/action.yml
@@ -15,8 +15,9 @@ inputs:
     default: ""
     description: "The tag of an artifact to deploy"
   target-repository:
-    description: "The name of the repository (e.g., `pirates-iac`) to checkout code from"
-    required: true
+    description: "The name of the repository (e.g., `pirates-iac`) to checkout code from. Leave empty to skip checkout and use the current repository."
+    required: false
+    default: ${{ github.event.repository.name }}
   github-app-id:
     description: "ID of GitHub App used to get read access to the repository containing IaC"
     required: true
@@ -37,9 +38,31 @@ outputs:
 runs:
   using: composite
   steps:
+    - name: Get stack directory
+      id: get-stack-dir
+      shell: bash --noprofile --norc -euo pipefail {0}
+      env:
+        EVENT_REPO: ${{ github.event.repository.name }}
+        REPO: ${{ inputs.target-repository }}
+        STACK_DIR: ${{ inputs.stack-dir }}
+      run: |
+        echo Get stack directory
+        
+        if [[ "${REPO}" == "${EVENT_REPO}" ]]; then
+          echo "stack-dir=$STACK_DIR" >> "$GITHUB_OUTPUT"
+          exit 0
+        fi
+        
+        checkout_path="tf-checkout-$(date +%s)"
+        full_dir="$checkout_path/$STACK_DIR"
+
+        echo "checkout-path=$checkout_path" >> "$GITHUB_OUTPUT"
+        echo "stack-dir=$full_dir" >> "$GITHUB_OUTPUT"
+
     - name: Get GitHub App token
+      if: inputs.target-repository != github.event.repository.name
       uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
-      id: get_token
+      id: get-token
       with:
         app-id: ${{ inputs.github-app-id }}
         private-key: ${{ inputs.github-app-private-key }}
@@ -47,13 +70,13 @@ runs:
         repositories: ${{ inputs.target-repository }}
 
     - name: Checkout
+      if: inputs.target-repository != github.event.repository.name
       uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
       id: checkout
       with:
         repository: "${{ github.repository_owner }}/${{ inputs.target-repository }}"
-        token: "${{ steps.get_token.outputs.token }}"
-        # TODO: A more unique name to avoid potentially reusing name of an existing folder?
-        path: "iac"
+        token: "${{ steps.get-token.outputs.token }}"
+        path: "${{ steps.get-stack-dir.outputs.checkout-path }}"
         fetch-depth: 1
 
     - name: Configure AWS credentials
@@ -70,8 +93,12 @@ runs:
     - name: Extract Terraform version
       id: v
       shell: bash --noprofile --norc -euo pipefail {0}
-      working-directory: iac/${{ inputs.stack-dir }}
-      run: ls -lah; echo "TERRAFORM_VERSION=$(grep required_version *.tf | sed -E 's/[^"]+"([^"]+)"+/\1/')" >> "$GITHUB_OUTPUT"
+      working-directory: ${{ steps.get-stack-dir.outputs.stack-dir }}
+      run: |
+        echo Extract Terraform version
+        pwd
+        ls -lah
+        echo "TERRAFORM_VERSION=$(grep required_version *.tf | sed -E 's/[^"]+"([^"]+)"+/\1/')" >> "$GITHUB_OUTPUT"
 
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
@@ -81,7 +108,7 @@ runs:
     - name: Initialize the working directory containing Terraform configuration files
       id: init
       shell: bash --noprofile --norc -euo pipefail {0}
-      working-directory: iac/${{ inputs.stack-dir }}
+      working-directory: ${{ steps.get-stack-dir.outputs.stack-dir }}
       continue-on-error: true
       run: |
         terraform init -input=false
@@ -107,9 +134,10 @@ runs:
           --overwrite
 
     - name: Verify that latest code is checked out
+      if: inputs.target-repository != github.event.repository.name
       shell: bash --noprofile --norc -euo pipefail {0}
       env:
-        GH_TOKEN: ${{ steps.get_token.outputs.token }}
+        GH_TOKEN: ${{ steps.get-token.outputs.token }}
         LOCAL_SHA: ${{ steps.checkout.outputs.commit }}
         REPOSITORY_OWNER: ${{ github.repository_owner }}
         TARGET_REPOSITORY: ${{ inputs.target-repository }}
@@ -129,7 +157,7 @@ runs:
       id: apply
       if: steps.init.outcome == 'success'
       shell: bash --noprofile --norc -euo pipefail {0}
-      working-directory: iac/${{ inputs.stack-dir }}
+      working-directory: ${{ steps.get-stack-dir.outputs.stack-dir }}
       run: |
         terraform apply -auto-approve -lock-timeout=5m
         result="$(terraform output -json \
